async function run() {
  const videoId = "jNQXAC9IVRw";
  const pipedInstances = [
    "https://pipedapi.moomoo.me",
    "https://pipedapi.kavin.rocks",
    "https://api.piped.projectsegfau.lt",
    "https://piped-api.garudalinux.org"
  ];
  
  let transcriptData = null;
  for (const instance of pipedInstances) {
    if (transcriptData) break;
    try {
      console.log(`[Transcript] Method: Piped API - Trying ${instance}`);
      const res = await fetch(`${instance}/streams/${videoId}`);
      if (!res.ok) {
        console.log("NOT OK", res.status);
        continue;
      }
      
      const data = await res.json();
      if (data && data.subtitles && Array.isArray(data.subtitles) && data.subtitles.length > 0) {
        let sub = data.subtitles.find((s: any) => s.code === 'en' && !s.autoGenerated);
        if (!sub) sub = data.subtitles.find((s: any) => s.code === 'en');
        if (!sub) sub = data.subtitles[0];
        
        if (sub && sub.url) {
            console.log("SUB URL:", sub.url);
            const vttRes = await fetch(sub.url);
            if (vttRes.ok) {
               const vttText = await vttRes.text();
               console.log("VTT", vttText.substring(0, 50));
               transcriptData = "found";
            }
        }
      } else {
        console.log("No subtitle data", data.subtitles);
      }
    } catch (e: any) {
      console.warn(`[Transcript] Piped API ${instance} Failed: ${e.message}`);
    }
  }
}
run();
