import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from "@google/genai";
import fetch from "node-fetch";
import { YoutubeTranscript } from 'youtube-transcript';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "empty" });

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { videoId } = req.query;
  if (!videoId || typeof videoId !== 'string') {
    return res.status(400).json({ error: 'Missing videoId' });
  }

  let transcriptData = null;

  try {
    const transcript = await YoutubeTranscript.fetchTranscript(videoId);
    
    if (transcript && transcript.length > 0) {
      transcriptData = transcript.map(t => ({
        text: t.text.replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"'),
        offset: t.offset,
        duration: t.duration
      }));
    }
  } catch (e: any) {
    if (!transcriptData) {
      const invidiousInstances = [
        "https://inv.thepixora.com",
        "https://yewtu.be",
        "https://vid.puffyan.us",
        "https://inv.tux.pizza"
      ];
      for (const instance of invidiousInstances) {
        if (transcriptData) break;
        try {
          const controller = new AbortController();
          const timeoutId = setTimeout(() => controller.abort(), 4000);
          const res = await fetch(`${instance}/api/v1/captions/${videoId}`, { signal: controller.signal });
          clearTimeout(timeoutId);
          if (!res.ok) continue;
          
          const data = await res.json() as any;
          if (data && data.captions && Array.isArray(data.captions) && data.captions.length > 0) {
            let selected = data.captions.find((c: any) => c.languageCode === "en" && !c.label?.toLowerCase().includes("auto-generated"));
            if (!selected) selected = data.captions.find((c: any) => c.languageCode === "en");
            if (!selected) selected = data.captions[0];
            
            if (selected) {
              let trackUrl = selected.url;
              if (trackUrl.startsWith("/")) {
                trackUrl = instance + trackUrl;
              }
              const trackRes = await fetch(trackUrl);
              if (trackRes.ok) {
                const vttText = await trackRes.text();
                const parsed = [];
                const vttLines = vttText.split('\n');
                let currentOffset = 0;
                let currentDuration = 0;
                
                for (let i = 0; i < vttLines.length; i++) {
                  const line = vttLines[i].trim();
                  if (line.includes('-->')) {
                     const parts = line.split('-->');
                     const parseTime = (t: string) => {
                       const p = t.split(':');
                       if (p.length === 3) return (parseFloat(p[0]) * 3600 + parseFloat(p[1]) * 60 + parseFloat(p[2])) * 1000;
                       if (p.length === 2) return (parseFloat(p[0]) * 60 + parseFloat(p[1])) * 1000;
                       return 0;
                     };
                     currentOffset = parseTime(parts[0].trim());
                     currentDuration = parseTime(parts[1].trim()) - currentOffset;
                  } else if (line && !line.includes('WEBVTT') && !line.match(/^[\d]+$/)) {
                     if (currentOffset > 0) {
                        parsed.push({
                           text: line.replace(/<[^>]+>/g, ''),
                           offset: currentOffset,
                           duration: currentDuration > 0 ? currentDuration : 3000
                        });
                        currentOffset = 0;
                     }
                  }
                }
                if (parsed.length > 0) {
                  transcriptData = parsed;
                }
              }
            }
          }
        } catch (err: any) {}
      }
    }

    if (!transcriptData) {
      const pipedInstances = [
        "https://pipedapi.moomoo.me",
        "https://pipedapi.kavin.rocks",
        "https://api.piped.projectsegfau.lt",
        "https://piped-api.garudalinux.org"
      ];
      
      for (const instance of pipedInstances) {
        if (transcriptData) break;
        try {
          const controller = new AbortController();
          const timeoutId = setTimeout(() => controller.abort(), 6000);
          const pRes = await fetch(`${instance}/streams/${videoId}`, { signal: controller.signal });
          clearTimeout(timeoutId);
          if (!pRes.ok) continue;
          
          const data = await pRes.json() as any;
          if (data && data.subtitles && Array.isArray(data.subtitles) && data.subtitles.length > 0) {
            let sub = data.subtitles.find((s: any) => s.code === 'en' && !s.autoGenerated);
            if (!sub) sub = data.subtitles.find((s: any) => s.code === 'en');
            if (!sub) sub = data.subtitles[0];
            
            if (sub && sub.url) {
                const vttRes = await fetch(sub.url);
                if (vttRes.ok) {
                   const vttText = await vttRes.text();
                   const parsed = [];
                   const vttLines = vttText.split('\n');
                   let currentOffset = 0;
                   let currentDuration = 0;
                   
                   for (let i = 0; i < vttLines.length; i++) {
                     const line = vttLines[i].trim();
                     if (line.includes('-->')) {
                        const parts = line.split('-->');
                        const start = parts[0].trim();
                        const end = parts[1].trim();
                        
                        const parseTime = (t: string) => {
                          const p = t.split(':');
                          if (p.length === 3) {
                             return (parseFloat(p[0]) * 3600 + parseFloat(p[1]) * 60 + parseFloat(p[2])) * 1000;
                          } else if (p.length === 2) {
                             return (parseFloat(p[0]) * 60 + parseFloat(p[1])) * 1000;
                          }
                          return 0;
                        };
                        currentOffset = parseTime(start);
                        currentDuration = parseTime(end) - currentOffset;
                     } else if (line && !line.includes('WEBVTT') && !line.match(/^[\d]+$/)) {
                        if (currentOffset > 0) {
                           parsed.push({
                              text: line.replace(/<[^>]+>/g, ''),
                              offset: currentOffset,
                              duration: currentDuration
                           });
                           currentOffset = 0;
                        }
                     }
                   }
                   if (parsed.length > 0) {
                     transcriptData = parsed;
                   }
                }
            }
          }
        } catch (e: any) {}
      }
    }
  }

  if (!transcriptData) {
    try {
      const searchResponse = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: `Search Google for the YouTube video with ID "${videoId}". Retrieve its title, description, and any available transcript, subtitles, or captions. Write down all details you can find or can confidently infer about the dialogue or topic/content of this video.`,
        config: {
          tools: [{ googleSearch: {} }]
        }
      });

      const searchResultText = searchResponse.text?.trim() || "";

      const structureResponse = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: `Below is some retrieved web-search information for a YouTube video of ID "${videoId}":
---
${searchResultText}
---

Your task is to extract or reconstruct a list of English sentences (representing the actual dialogue, narrated captions, or a highly natural verbal conversation matching the title, topic, and context of this video).
If you have found some transcript/subtitles in the search results, use them. If not, generate a sequence of 10-15 highly natural English conversational sentences that perfectly match the topic, level, and context of this video so the user can study it as an English learning dialogue.

You MUST format your output strictly as a JSON array of objects, with each object having the following keys:
- text: string (the English subtitle sentence)
- offset: number (approximate start time in milliseconds, starting at 1000 and incrementing by 5000-8000 ms per sentence)
- duration: number (duration in milliseconds, between 3000 and 6000 ms)

Example output format:
[
  {"text": "Hello, welcome back to the channel.", "offset": 1000, "duration": 4000},
  {"text": "Today, we are discussing daily English conversations.", "offset": 6000, "duration": 5000}
]`,
        config: {
          responseMimeType: "application/json"
        }
      });

      const text = structureResponse.text?.trim() || "";
      const cleanJson = text.replace(/^```json\n?|```$/g, "").trim();
      const parsed = JSON.parse(cleanJson);
      if (Array.isArray(parsed) && parsed.length > 0) {
        transcriptData = parsed.map((item: any) => ({
          text: item.text || item.sentence || "",
          offset: parseInt(item.offset || "0"),
          duration: parseInt(item.duration || "4000")
        }));
      }
    } catch (e: any) {
      try {
        const normalResponse = await ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: `Generate a list of 10-15 beautiful, natural, conversational English learning dialogue sentences on the topic of standard daily communication.
Format the output strictly as a JSON array where each object has:
- text: string (English sentence)
- offset: number (start in ms, e.g. 1000, 6000, 12000, ...)
- duration: number (duration in ms, e.g. 4000, 5000, ...)`,
          config: {
            responseMimeType: "application/json"
          }
        });
        const textRes = normalResponse.text?.trim() || "";
        const cleanJson = textRes.replace(/^```json\n?|```$/g, "").trim();
        const parsed = JSON.parse(cleanJson);
        if (Array.isArray(parsed) && parsed.length > 0) {
          transcriptData = parsed.map((item: any) => ({
            text: item.text || item.sentence || "",
            offset: parseInt(item.offset || "0"),
            duration: parseInt(item.duration || "4000")
          }));
        }
      } catch (ee: any) {
      }
    }
  }

  if (!transcriptData) {
    transcriptData = [
      { text: "Welcome to this language learning session.", offset: 1000, duration: 4000 },
      { text: "We could not find the exact subtitles for this video.", offset: 6000, duration: 4000 },
      { text: "But you can still use the audio to practice shadowing and listening.", offset: 11000, duration: 5000 },
      { text: "Keep pushing forward, you are doing great!", offset: 17000, duration: 4000 }
    ];
  }

  return res.status(200).json({ transcript: transcriptData });
}
